package com.dungphd.insurance.model;

public enum TransactionType {
    CREATE_POLICY,
    UPDATE_POLICY,
    STATUS_TRANSITION,
    ENDORSEMENT,
    ADD_LOCATION,
    UPDATE_LOCATION,
    REMOVE_LOCATION,
    ADD_COVERAGE,
    UPDATE_COVERAGE,
    REMOVE_COVERAGE,
    CANCEL_POLICY,
    EXPIRE_POLICY
}
